server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loverblue?charsacterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.loverblue.hr.bean
users:
  id: 1
  userName: xiaohong
  possword: xiaoming
logging:
  level:
   root: info
  file:
    path: log
pagehelper:
  helper-dialect: mysql



